import axios from "axios";
import { API_URL } from "../../../config";
import React from "react";
import { useEffect, useState, useRef, useMemo } from "react";

import TinderCard from "react-tinder-card";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
const ShufflePage = () => {
  //Setters
  const [imageSample, setImageSample] = useState([]);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);

  // const imageSample = [
  //   {
  //     _id: "675a959f85fdaca18e373362",
  //     photo_id: "XkheksZnNT4",
  //     photo_url: "https://unsplash.com/photos/XkheksZnNT4",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1549415697-8e9a0872f910",
  //     photo_submitted_at: "2019-02-06 01:15:42.418676",
  //     photo_featured: "t",
  //     photo_width: "4000",
  //     photo_height: "6000",
  //     photo_aspect_ratio: "0.67000000000000004",
  //     photo_description: "",
  //     photographer_username: "hb5__",
  //     photographer_first_name: "Holden",
  //     photographer_last_name: "Baxter",
  //     exif_camera_make: "SONY",
  //     exif_camera_model: "ILCE-7",
  //     exif_iso: "800",
  //     exif_aperture_value: "5.6",
  //     exif_focal_length: "50.0",
  //     exif_exposure_time: "1/1250",
  //     photo_location_name: "Great Sand Dunes",
  //     photo_location_latitude: "",
  //     photo_location_longitude: "",
  //     photo_location_country: "",
  //     photo_location_city: "",
  //     stats_views: "700738",
  //     stats_downloads: "4520",
  //     ai_description: "gold-colored desert",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "LwJHmvxaofj[?wt7j[j[.8s:RkoL",
  //     colors: [
  //       "49382C",
  //       "AB896D",
  //       "AE9177",
  //       "9D7A5D",
  //       "93775F",
  //       "381801",
  //       "43362D",
  //       "D0BBA5",
  //       "5A493A",
  //       "F8FBF9",
  //     ],
  //     keywords: [
  //       "vacation",
  //       "vehicle",
  //       "astronomy",
  //       "broom",
  //       "bag",
  //       "sign",
  //       "tripod",
  //       "animal",
  //       "cap",
  //       "tree stump",
  //       "hourglass",
  //       "backpack",
  //       "natural environment",
  //       "space",
  //       "whip",
  //       "universe",
  //       "monitor",
  //       "hill",
  //       "finger",
  //       "lcd screen",
  //       "hook",
  //       "wilderness",
  //       "art",
  //       "milk",
  //       "footsteps",
  //       "adventure",
  //       "mesa",
  //       "wildlife",
  //       "shoe",
  //       "baseball cap",
  //       "rural",
  //       "shorts",
  //       "shop",
  //       "drink",
  //       "accessories",
  //       "dune",
  //       "blossom",
  //       "ground",
  //       "dress",
  //       "hat",
  //       "bread",
  //       "alcohol",
  //       "food",
  //       "human",
  //       "wrist",
  //       "offroad",
  //       "blanket",
  //       "building",
  //       "screen",
  //       "powder",
  //       "hand",
  //       "symbol",
  //       "weather",
  //       "aeolian landform",
  //       "countryside",
  //       "sony",
  //       "hiking",
  //       "heart",
  //       "footprint",
  //       "sand",
  //       "mammal",
  //       "water",
  //       "accessory",
  //       "lighthouse",
  //       "tower",
  //       "land",
  //       "ball",
  //       "beer",
  //       "glove",
  //       "apparel",
  //       "dunes",
  //       "planet",
  //       "snow",
  //       "display",
  //       "electrical device",
  //       "nature",
  //       "leisure activities",
  //       "sneaker",
  //       "lost",
  //       "pyramid",
  //       "footwear",
  //       "skeleton",
  //       "architecture",
  //       "trail",
  //       "mouth",
  //       "sky",
  //       "underwater",
  //       "american flag",
  //       "beacon",
  //       "pants",
  //       "antenna",
  //       "desert",
  //       "walking",
  //       "sunflower",
  //       "transportation",
  //       "ripple",
  //       "flag",
  //       "person",
  //       "cloak",
  //       "tool",
  //       "moon",
  //       "slope",
  //       "canopy",
  //       "balloon",
  //       "electronics",
  //       "plant",
  //       "fashion",
  //       "bird",
  //       "flower",
  //       "gray",
  //       "hole",
  //       "buggy",
  //       "earring",
  //       "hot air balloon",
  //       "summer",
  //       "hut",
  //       "camel",
  //       "beverage",
  //       "light",
  //       "anchor",
  //       "jewelry",
  //       "dodo",
  //       "singing sand",
  //       "scenery",
  //       "night",
  //       "sunglasses",
  //       "clothing",
  //       "photographer",
  //       "hammer",
  //       "outdoors",
  //       "necklace",
  //       "erg",
  //       "floor",
  //       "lip",
  //       "stretch",
  //       "shoulder",
  //       "phone",
  //       "outer space",
  //       "soil",
  //       "pigeon",
  //       "aircraft",
  //       "landscape",
  //       "thumbs up",
  //     ],
  //   },
  //   {
  //     _id: "675a959f85fdaca18e3738c3",
  //     photo_id: "tZls4_oGkqE",
  //     photo_url: "https://unsplash.com/photos/tZls4_oGkqE",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1474390690775-517486716e55",
  //     photo_submitted_at: "2016-09-20 16:58:46.05651",
  //     photo_featured: "t",
  //     photo_width: "4928",
  //     photo_height: "3264",
  //     photo_aspect_ratio: "1.51",
  //     photo_description: "Surfer silhouettes on Cannon Beach",
  //     photographer_username: "jamomca",
  //     photographer_first_name: "Jamison",
  //     photographer_last_name: "McAndie",
  //     exif_camera_make: "NIKON CORPORATION",
  //     exif_camera_model: "NIKON D7000",
  //     exif_iso: "100",
  //     exif_aperture_value: "10.0",
  //     exif_focal_length: "62.0",
  //     exif_exposure_time: "1/400",
  //     photo_location_name: "Cannon Beach, United States",
  //     photo_location_latitude: "-123.9615274",
  //     photo_location_longitude: "45.8917738",
  //     photo_location_country: "United States",
  //     photo_location_city: "Cannon Beach",
  //     stats_views: "3748084",
  //     stats_downloads: "19465",
  //     ai_description: "two men carrying surfboards near body of water",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "LNNwvQ^*Rjt7pKj@jZay0MWCoLay",
  //     colors: [
  //       "30302E",
  //       "CCD0D3",
  //       "555554",
  //       "C4D5E4",
  //       "9CA0A2",
  //       "1E1E25",
  //       "E1E6E9",
  //       "828384",
  //     ],
  //     keywords: [
  //       "soil",
  //       "people",
  //       "white",
  //       "pale",
  //       "surfboard",
  //       "water sports",
  //       "bright",
  //       "walking",
  //       "person",
  //       "couple",
  //       "coastline",
  //       "silhouette",
  //       "beach walking",
  //       "waves",
  //       "surfer",
  //       "east coast",
  //       "fog",
  //       "horizon",
  //       "weather",
  //       "white space",
  //       "atmospheric phenomenon",
  //       "surf board",
  //       "mist",
  //       "sunny day",
  //       "walk",
  //       "surfing",
  //       "wafe",
  //       "california",
  //       "sea",
  //       "sand",
  //       "horizon line",
  //       "sea side",
  //       "shore",
  //       "wide landscape",
  //       "mirror",
  //       "surf boards",
  //       "coast",
  //       "two",
  //       "human",
  //       "nature",
  //       "west coast",
  //       "morning",
  //       "vacation",
  //       "surf",
  //       "leisure activities",
  //       "cliff",
  //       "ocean",
  //       "water",
  //       "wet",
  //       "scenery",
  //       "winter",
  //       "water boarding",
  //       "beach",
  //       "landscape",
  //       "rock",
  //       "outdoors",
  //       "swimming",
  //       "head",
  //     ],
  //   },
  //   {
  //     _id: "675a95a285fdaca18e376072",
  //     photo_id: "_vUQD2qFcIY",
  //     photo_url: "https://unsplash.com/photos/_vUQD2qFcIY",
  //     photo_image_url:
  //       "https://images.unsplash.com/flagged/photo-1576199621331-61d3121da206",
  //     photo_submitted_at: "2019-12-13 01:14:42.010527",
  //     photo_featured: "t",
  //     photo_width: "4000",
  //     photo_height: "6000",
  //     photo_aspect_ratio: "0.67000000000000004",
  //     photo_description: "Jellyfish jellyfish, look at the red and blue",
  //     photographer_username: "ronaldwong57",
  //     photographer_first_name: "Ronald",
  //     photographer_last_name: "Wong",
  //     exif_camera_make: "NIKON CORPORATION",
  //     exif_camera_model: "NIKON D5300",
  //     exif_iso: "400",
  //     exif_aperture_value: "2",
  //     exif_focal_length: "35.0",
  //     exif_exposure_time: "1/125",
  //     photo_location_name:
  //       "Ripley's Aquarium of Canada, Bremner Boulevard, Toronto, ON, Canada",
  //     photo_location_latitude: "-79.3859716",
  //     photo_location_longitude: "43.6424036",
  //     photo_location_country: "Canada",
  //     photo_location_city: "Toronto",
  //     stats_views: "114576",
  //     stats_downloads: "1143",
  //     ai_description: "underwater photography of red jellyfish",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "LLBJ$-oLJHWabLoIawWZE=b0w;oG",
  //     colors: [
  //       "6E18E9",
  //       "B038CD",
  //       "A941EE",
  //       "8F22B0",
  //       "7B21A2",
  //       "550C85",
  //       "8026CB",
  //       "660BFC",
  //       "7519FB",
  //       "8D37FC",
  //     ],
  //     keywords: [
  //       "organism",
  //       "raspberry",
  //       "apidae",
  //       "bee",
  //       "plant",
  //       "sea life",
  //       "aquarium",
  //       "blue",
  //       "fish",
  //       "handwriting",
  //       "snorkeling",
  //       "jay",
  //       "alcohol",
  //       "magenta",
  //       "vine",
  //       "diver",
  //       "purple",
  //       "violet",
  //       "marine invertebrates",
  //       "water",
  //       "ball",
  //       "reptile",
  //       "french toast",
  //       "iris",
  //       "oyster",
  //       "towel",
  //       "octopus",
  //       "red",
  //       "jellyfish",
  //       "gray",
  //       "swordfish",
  //       "bird",
  //       "snake",
  //       "paper",
  //       "marine biology",
  //       "cherry",
  //       "compass math",
  //       "weaponry",
  //       "contrast",
  //       "sports",
  //       "bread",
  //       "food",
  //       "ocean",
  //       "flower",
  //       "riding boot",
  //       "sport",
  //       "animal",
  //       "blade",
  //       "weapon",
  //       "beer",
  //       "tuna",
  //       "shark",
  //       "wildlife",
  //       "applique",
  //       "balloon",
  //       "cutlery",
  //       "outdoors",
  //       "pollen",
  //       "clothing",
  //       "angelfish",
  //       "seahorse",
  //       "fork",
  //       "peacock",
  //       "toast",
  //       "blossom",
  //       "text",
  //       "scorpion",
  //       "handle",
  //       "human",
  //       "invertebrate",
  //       "clam",
  //       "sea",
  //       "seashell",
  //       "person",
  //       "drink",
  //       "geranium",
  //       "beverage",
  //       "peach",
  //       "apparel",
  //       "sea anemone",
  //       "bucket",
  //       "underwater",
  //       "cnidaria",
  //       "boot",
  //       "plastic",
  //       "sponge animal",
  //       "footwear",
  //       "diagram",
  //       "mammal",
  //       "diving",
  //       "fruit",
  //       "manta ray",
  //       "nature",
  //       "starfish",
  //       "paper towel",
  //       "aquatic",
  //       "ant",
  //       "inflatable",
  //       "insect",
  //     ],
  //   },
  //   {
  //     _id: "675a959e85fdaca18e372e66",
  //     photo_id: "PdJjT-zYg_E",
  //     photo_url: "https://unsplash.com/photos/PdJjT-zYg_E",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1467780839816-65e92876c0bd",
  //     photo_submitted_at: "2016-07-06 04:55:09.248179",
  //     photo_featured: "t",
  //     photo_width: "5384",
  //     photo_height: "3589",
  //     photo_aspect_ratio: "1.5",
  //     photo_description: "",
  //     photographer_username: "ryanhafey",
  //     photographer_first_name: "Ryan",
  //     photographer_last_name: "Hafey",
  //     exif_camera_make: "Canon",
  //     exif_camera_model: "Canon EOS 7D Mark II",
  //     exif_iso: "100",
  //     exif_aperture_value: "4.0",
  //     exif_focal_length: "70.0",
  //     exif_exposure_time: "1/160",
  //     photo_location_name: "Edwards, United States",
  //     photo_location_latitude: "-89.7489531",
  //     photo_location_longitude: "40.7455683",
  //     photo_location_country: "United States",
  //     photo_location_city: "Edwards",
  //     stats_views: "7164745",
  //     stats_downloads: "104288",
  //     ai_description: "photo of swing chair on tree",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "LECQF~ozIBIB4:ocR+t74UM|t7of",
  //     colors: [
  //       "9ba288",
  //       "52514b",
  //       "c7c7ab",
  //       "6e7e5d",
  //       "393731",
  //       "b6c39e",
  //       "92a07d",
  //       "4b5c3e",
  //       "687c70",
  //       "ece8ce",
  //     ],
  //     keywords: [
  //       "branch",
  //       "country",
  //       "rainforest",
  //       "yard",
  //       "sycamore",
  //       "flora",
  //       "land",
  //       "swing",
  //       "feeder",
  //       "red",
  //       "summer fun",
  //       "bough",
  //       "grove",
  //       "outdoors",
  //       "tree",
  //       "hummingbird",
  //       "forest",
  //       "trunk",
  //       "bark",
  //       "vegetation",
  //       "nature",
  //       "bird feeder",
  //       "wood",
  //       "conifer",
  //       "plant",
  //       "swinging",
  //       "redwood",
  //       "landscape",
  //       "old tree",
  //       "tree swing",
  //       "shade",
  //       "yew",
  //       "tree trunk",
  //       "big tree",
  //       "park",
  //       "field",
  //       "jungle",
  //       "woodland",
  //       "grass",
  //       "lawn",
  //       "oak",
  //       "green",
  //       "garden",
  //     ],
  //   },
  //   {
  //     _id: "675a959d85fdaca18e372b02",
  //     photo_id: "V7M6_dpf9TU",
  //     photo_url: "https://unsplash.com/photos/V7M6_dpf9TU",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1589000641018-435c761030b2",
  //     photo_submitted_at: "2020-05-09 05:05:17.224581",
  //     photo_featured: "t",
  //     photo_width: "5277",
  //     photo_height: "3518",
  //     photo_aspect_ratio: "1.5",
  //     photo_description: "",
  //     photographer_username: "vinomamba24",
  //     photographer_first_name: "Vino",
  //     photographer_last_name: "Li",
  //     exif_camera_make: "Canon",
  //     exif_camera_model: "Canon EOS 6D",
  //     exif_iso: "200",
  //     exif_aperture_value: "2.8",
  //     exif_focal_length: "50.0",
  //     exif_exposure_time: "1/160",
  //     photo_location_name: "",
  //     photo_location_latitude: "",
  //     photo_location_longitude: "",
  //     photo_location_country: "",
  //     photo_location_city: "",
  //     stats_views: "732211",
  //     stats_downloads: "3819",
  //     ai_description: "green leaf in close up photography",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "LFB5U38#i~bFt5tPoxV]oykAV]ox",
  //     colors: [
  //       "7FAE4E",
  //       "58863D",
  //       "15380F",
  //       "98C46F",
  //       "3A5F33",
  //       "597F4E",
  //       "174308",
  //       "376424",
  //       "062203",
  //       "78A654",
  //     ],
  //     keywords: [
  //       "botany",
  //       "close-up",
  //       "flower",
  //       "lace",
  //       "flagstone",
  //       "sunlight",
  //       "pendant",
  //       "fern",
  //       "texture",
  //       "bag",
  //       "umbrella",
  //       "tree",
  //       "plastic bag",
  //       "furniture",
  //       "water",
  //       "algae",
  //       "curtain",
  //       "blossom",
  //       "french door",
  //       "kiss",
  //       "medication",
  //       "maroon",
  //       "gladiolus",
  //       "wildlife",
  //       "bamboo",
  //       "droplet",
  //       "pill",
  //       "white",
  //       "outdoors",
  //       "ivy",
  //       "salamander",
  //       "fence",
  //       "pattern",
  //       "plastic",
  //       "zipper",
  //       "crystal",
  //       "canopy",
  //       "broom",
  //       "bow",
  //       "kissing",
  //       "line",
  //       "veins",
  //       "amphibian",
  //       "art",
  //       "moss",
  //       "ripple",
  //       "stick",
  //       "fish",
  //       "porch",
  //       "file",
  //       "paper",
  //       "ornament",
  //       "maple",
  //       "skin",
  //       "leaf",
  //       "green",
  //       "lily",
  //       "bookcase",
  //       "parallel",
  //       "maple leaf",
  //       "hedge",
  //       "anthurium",
  //       "plant",
  //       "goldfish",
  //       "tattoo",
  //       "animal",
  //       "compass math",
  //       "tints and shades",
  //       "purple",
  //       "hole",
  //       "fractal",
  //       "photo",
  //       "photography",
  //       "stained glass",
  //       "dragon",
  //       "ground",
  //     ],
  //   },
  //   {
  //     _id: "675a95a185fdaca18e37545a",
  //     photo_id: "0Z4lIZ7qSyQ",
  //     photo_url: "https://unsplash.com/photos/0Z4lIZ7qSyQ",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1516371957266-763acedfa595",
  //     photo_submitted_at: "2018-01-19 14:26:28.056728",
  //     photo_featured: "t",
  //     photo_width: "4000",
  //     photo_height: "6000",
  //     photo_aspect_ratio: "0.67000000000000004",
  //     photo_description: "",
  //     photographer_username: "leshamakogon",
  //     photographer_first_name: "Lesha",
  //     photographer_last_name: "Makogon",
  //     exif_camera_make: "SONY",
  //     exif_camera_model: "ILCE-6000",
  //     exif_iso: "200",
  //     exif_aperture_value: "6.3",
  //     exif_focal_length: "20.0",
  //     exif_exposure_time: "1/80",
  //     photo_location_name: "",
  //     photo_location_latitude: "",
  //     photo_location_longitude: "",
  //     photo_location_country: "",
  //     photo_location_city: "",
  //     stats_views: "556824",
  //     stats_downloads: "2665",
  //     ai_description: "firewood lot",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "L7EVE6oJR-ae4:t7ofWV0Kj?j[n~",
  //     colors: [
  //       "1a0d06",
  //       "857870",
  //       "beb3ac",
  //       "423122",
  //       "a79b94",
  //       "60534c",
  //       "8f6d55",
  //       "655140",
  //       "a99483",
  //       "8c7662",
  //     ],
  //     keywords: [
  //       "woodland",
  //       "material",
  //       "texture",
  //       "soil",
  //       "sidewalk",
  //       "rubble",
  //       "logs",
  //       "forest",
  //       "tree",
  //       "stone wall",
  //       "log pile",
  //       "ground",
  //       "path",
  //       "wood",
  //       "roof",
  //       "cobblestone",
  //       "pavement",
  //       "grain",
  //       "rock",
  //       "walkway",
  //       "pattern",
  //     ],
  //   },
  //   {
  //     _id: "675a95a285fdaca18e375afd",
  //     photo_id: "uyHE0u8_Ruw",
  //     photo_url: "https://unsplash.com/photos/uyHE0u8_Ruw",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1588762549983-21f70cb26daf",
  //     photo_submitted_at: "2020-05-06 10:57:01.164576",
  //     photo_featured: "t",
  //     photo_width: "3456",
  //     photo_height: "5184",
  //     photo_aspect_ratio: "0.67000000000000004",
  //     photo_description:
  //       "close up of an tropical outdoor plant in the sunshine (succulents)",
  //     photographer_username: "katetrifo",
  //     photographer_first_name: "Kate",
  //     photographer_last_name: "Trifo",
  //     exif_camera_make: "Canon",
  //     exif_camera_model: "Canon EOS REBEL T2i",
  //     exif_iso: "200",
  //     exif_aperture_value: "4.5",
  //     exif_focal_length: "35.0",
  //     exif_exposure_time: "1/640",
  //     photo_location_name: "Cremorne NSW, Australia",
  //     photo_location_latitude: "151.227628",
  //     photo_location_longitude: "-33.826534",
  //     photo_location_country: "Australia",
  //     photo_location_city: "Cremorne",
  //     stats_views: "660275",
  //     stats_downloads: "2128",
  //     ai_description: "green and brown plant leaves",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "L59Z_sNHE2M}~ooft6R*IW%1?Gxt",
  //     colors: [
  //       "7C725C",
  //       "1D1D14",
  //       "262113",
  //       "555347",
  //       "3D3928",
  //       "8D8A7E",
  //       "625B45",
  //       "36362B",
  //       "7C776A",
  //       "978C78",
  //     ],
  //     keywords: [
  //       "amphibian",
  //       "cross",
  //       "urban",
  //       "purple",
  //       "summer",
  //       "can",
  //       "greenhouse",
  //       "life buoy",
  //       "spiral",
  //       "bulldog",
  //       "vegetation",
  //       "clothing",
  //       "terrace",
  //       "plant",
  //       "leopard",
  //       "balcony",
  //       "perennial plant",
  //       "leaf",
  //       "candle",
  //       "conifer",
  //       "accessories",
  //       "maze",
  //       "weaponry",
  //       "ground",
  //       "cable",
  //       "tower",
  //       "spear",
  //       "peacock",
  //       "railing",
  //       "modern art",
  //       "school",
  //       "weapon",
  //       "coin",
  //       "walking",
  //       "photographer",
  //       "agavaceae",
  //       "accessory",
  //       "staircase",
  //       "yew",
  //       "lab",
  //       "jar",
  //       "teen",
  //       "pebble",
  //       "bush",
  //       "wildlife",
  //       "antelope",
  //       "flower",
  //       "panther",
  //       "grasshopper",
  //       "female",
  //       "labyrinth",
  //       "vase",
  //       "grasshoper",
  //       "sign",
  //       "acanthaceae",
  //       "tree",
  //       "high heel",
  //       "porcupine",
  //       "architecture",
  //       "woman",
  //       "first aid",
  //       "gray",
  //       "neighborhood",
  //       "algae",
  //       "dog",
  //       "pottery",
  //       "kid",
  //       "droplet",
  //       "bottle",
  //       "mammal",
  //       "shoe",
  //       "araceae",
  //       "slate",
  //       "apparel",
  //       "pot",
  //       "hole",
  //       "housing",
  //       "home decor",
  //       "turquoise",
  //       "sliced",
  //       "animal",
  //       "money",
  //       "clock",
  //       "weed",
  //       "clock tower",
  //       "sycamore",
  //       "demolition",
  //       "concrete",
  //       "fence",
  //       "petal",
  //       "child",
  //       "blossom",
  //       "pearl",
  //       "audience",
  //       "invertebrate",
  //       "road sign",
  //       "broom",
  //       "graduation",
  //       "botany",
  //       "canine",
  //       "pet",
  //       "building",
  //       "flowering plant",
  //       "sunlight",
  //       "succulent plant",
  //       "winter",
  //       "digital clock",
  //       "magnolia",
  //       "rodent",
  //       "aloe",
  //       "agave",
  //       "lamp post",
  //       "linen",
  //       "private mailbox",
  //       "tin",
  //       "oak",
  //       "bunker",
  //       "footwear",
  //       "spider",
  //       "jewelry",
  //       "crowd",
  //       "bird",
  //       "art",
  //       "brick",
  //       "wood",
  //       "driftwood",
  //       "root",
  //       "inflatable",
  //       "jaguar",
  //       "cactus",
  //       "soil",
  //       "arachnid",
  //       "electric fan",
  //       "power lines",
  //       "symbol",
  //       "insect",
  //       "picket",
  //       "tire",
  //     ],
  //   },
  //   {
  //     _id: "675a959f85fdaca18e37343b",
  //     photo_id: "cmyDyDa6Wfk",
  //     photo_url: "https://unsplash.com/photos/cmyDyDa6Wfk",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1551623063-9ce62b2eb8c3",
  //     photo_submitted_at: "2019-03-03 14:24:38.36913",
  //     photo_featured: "t",
  //     photo_width: "3456",
  //     photo_height: "5184",
  //     photo_aspect_ratio: "0.67000000000000004",
  //     photo_description: "",
  //     photographer_username: "matreding",
  //     photographer_first_name: "Mathias",
  //     photographer_last_name: "Reding",
  //     exif_camera_make: "Canon",
  //     exif_camera_model: "Canon EOS 600D",
  //     exif_iso: "100",
  //     exif_aperture_value: "7.1",
  //     exif_focal_length: "18.0",
  //     exif_exposure_time: "1/125",
  //     photo_location_name: "",
  //     photo_location_latitude: "",
  //     photo_location_longitude: "",
  //     photo_location_country: "",
  //     photo_location_city: "",
  //     stats_views: "9032510",
  //     stats_downloads: "36451",
  //     ai_description: "landscape photography of green mountain",
  //     ai_primary_landmark_name: "Mer de Glace",
  //     ai_primary_landmark_latitude: "45.930864999999997",
  //     ai_primary_landmark_longitude: "6.9181249999999999",
  //     ai_primary_landmark_confidence: "0.50816327333450317",
  //     blur_hash: "LoG[+txuV@oe?wR*WBoLo~Rkt7of",
  //     colors: [
  //       "AD9686",
  //       "BEC2CA",
  //       "837772",
  //       "3C311E",
  //       "AEC0CF",
  //       "635242",
  //       "8B7767",
  //       "CAB3A3",
  //       "9F9A9C",
  //       "98A5B6",
  //     ],
  //     keywords: [
  //       "cannon",
  //       "pine",
  //       "coke",
  //       "ice",
  //       "cable",
  //       "road sign",
  //       "flower",
  //       "aluminium",
  //       "wallpapers",
  //       "valley",
  //       "apparel",
  //       "plant",
  //       "scenery",
  //       "bicycle",
  //       "sky",
  //       "sunlight",
  //       "maple",
  //       "hill",
  //       "flag",
  //       "building",
  //       "canopy",
  //       "plateau",
  //       "bag",
  //       "conifer",
  //       "abies",
  //       "tent",
  //       "ground",
  //       "footwear",
  //       "outdoors",
  //       "leisure activities",
  //       "explore",
  //       "sports",
  //       "house",
  //       "photographer",
  //       "transportation",
  //       "spruce",
  //       "wheel",
  //       "ball",
  //       "weaponry",
  //       "tripod",
  //       "tarmac",
  //       "geranium",
  //       "wallpaper",
  //       "cliff",
  //       "bike",
  //       "accessory",
  //       "coca",
  //       "smoke",
  //       "landscape",
  //       "volcano",
  //       "mountain tent",
  //       "outdoor",
  //       "larch",
  //       "water",
  //       "adventure",
  //       "hole",
  //       "stopsign",
  //       "promontory",
  //       "tub",
  //       "hut",
  //       "high heel",
  //       "natural landscape",
  //       "granite",
  //       "van",
  //       "mountain range",
  //       "accessories",
  //       "rail",
  //       "asphalt",
  //       "countryside",
  //       "tree",
  //       "fern",
  //       "backpack",
  //       "flagstone",
  //       "gravel",
  //       "beverage",
  //       "tree stump",
  //       "geological phenomenon",
  //       "shoe",
  //       "symbol",
  //       "crater",
  //       "drink",
  //       "glacier",
  //       "lake",
  //       "mountain",
  //       "tank top",
  //       "tire",
  //       "train track",
  //       "staircase",
  //       "balloon",
  //       "fir",
  //       "wilderness",
  //       "soil",
  //       "sunglasses",
  //       "shipping container",
  //       "desert",
  //       "bunker",
  //       "freeway",
  //       "slope",
  //       "backgrounds",
  //       "canyon",
  //       "box",
  //       "pet",
  //       "trail",
  //       "road",
  //       "rv",
  //       "sport",
  //       "grass",
  //       "rubble",
  //       "highway",
  //       "animal",
  //       "mountain pass",
  //       "mountainous landforms",
  //       "sign",
  //       "housing",
  //       "snow",
  //       "aerial view",
  //       "awning",
  //       "rural",
  //       "velvet",
  //       "vehicle",
  //       "path",
  //       "camping",
  //       "highland",
  //       "blossom",
  //       "basin",
  //       "railway",
  //       "weapon",
  //       "dirt road",
  //       "bus",
  //       "sphere",
  //       "landslide",
  //       "nature",
  //       "clothing",
  //       "machine",
  //       "lawn",
  //       "green",
  //       "cabin",
  //     ],
  //   },
  //   {
  //     _id: "675a95a185fdaca18e375393",
  //     photo_id: "-KNNQqX9rqY",
  //     photo_url: "https://unsplash.com/photos/-KNNQqX9rqY",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1477764250597-dffe9f601ae8",
  //     photo_submitted_at: "2016-10-29 18:04:34.284658",
  //     photo_featured: "t",
  //     photo_width: "3720",
  //     photo_height: "2480",
  //     photo_aspect_ratio: "1.5",
  //     photo_description: "Tiger in a zoo",
  //     photographer_username: "nickkarvounis",
  //     photographer_first_name: "Nick",
  //     photographer_last_name: "Karvounis",
  //     exif_camera_make: "Canon",
  //     exif_camera_model: "Canon EOS 5D Mark III",
  //     exif_iso: "640",
  //     exif_aperture_value: "5.6",
  //     exif_focal_length: "280.0",
  //     exif_exposure_time: "1/500",
  //     photo_location_name: "Copenhagen, Denmark",
  //     photo_location_latitude: "12.5683371",
  //     photo_location_longitude: "55.6760968",
  //     photo_location_country: "Denmark",
  //     photo_location_city: "Copenhagen",
  //     stats_views: "16162041",
  //     stats_downloads: "171953",
  //     ai_description: "orange tiger on grey concrete flooring",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "LIE33WWs0gn#S]D*jFxt9[RP$$tR",
  //     colors: [
  //       "986e56",
  //       "4e2b19",
  //       "724c36",
  //       "7f4924",
  //       "a66c43",
  //       "e3ac7d",
  //       "cb9062",
  //       "d3bca2",
  //       "e2b499",
  //       "bc9176",
  //     ],
  //     keywords: [
  //       "pet",
  //       "fur",
  //       "stripe",
  //       "predator",
  //       "head",
  //       "jungle",
  //       "fauna",
  //       "big cat",
  //       "hunter",
  //       "cat",
  //       "animal",
  //       "whisker",
  //       "tiger",
  //       "mammal",
  //       "zoo",
  //       "carnivore",
  //       "striped",
  //       "feline",
  //       "tigress",
  //       "wildlife",
  //     ],
  //   },
  //   {
  //     _id: "675a959d85fdaca18e372a9d",
  //     photo_id: "qSGqR5WvOnU",
  //     photo_url: "https://unsplash.com/photos/qSGqR5WvOnU",
  //     photo_image_url:
  //       "https://images.unsplash.com/photo-1508610232556-b13ab6d792b2",
  //     photo_submitted_at: "2017-10-21 18:25:30.904704",
  //     photo_featured: "t",
  //     photo_width: "4411",
  //     photo_height: "3266",
  //     photo_aspect_ratio: "1.3500000000000001",
  //     photo_description: "",
  //     photographer_username: "jamie452",
  //     photographer_first_name: "Jamie",
  //     photographer_last_name: "Street",
  //     exif_camera_make: "Panasonic",
  //     exif_camera_model: "DC-GH5",
  //     exif_iso: "400",
  //     exif_aperture_value: "1.2",
  //     exif_focal_length: "43.0",
  //     exif_exposure_time: "1/200",
  //     photo_location_name:
  //       "Surrey Hills Area of Outstanding Natural Beauty, Dorking, United Kingdom",
  //     photo_location_latitude: "-0.311950000000024",
  //     photo_location_longitude: "51.253113",
  //     photo_location_country: "United Kingdom",
  //     photo_location_city: "Dorking",
  //     stats_views: "5041432",
  //     stats_downloads: "30465",
  //     ai_description: "selective focus photography of sparklers",
  //     ai_primary_landmark_name: "",
  //     ai_primary_landmark_latitude: "",
  //     ai_primary_landmark_longitude: "",
  //     ai_primary_landmark_confidence: "",
  //     blur_hash: "L76t,qtQ0MICpHxaVtIVIpWV%1od",
  //     colors: [
  //       "c0967a",
  //       "d0c2a6",
  //       "462f36",
  //       "7d7a63",
  //       "51504a",
  //       "5e5141",
  //       "3b373b",
  //       "946c52",
  //       "754e39",
  //       "9a9a7f",
  //     ],
  //     keywords: [
  //       "blur",
  //       "twig",
  //       "ground",
  //       "atmosphere",
  //       "leaf",
  //       "wood",
  //       "outdoor",
  //       "phenomenon",
  //       "plant",
  //       "forest",
  //       "twigs",
  //       "water",
  //       "darkness",
  //       "dirt road",
  //       "fallen leaves",
  //       "weed",
  //       "grass",
  //       "joy",
  //       "road",
  //       "sky",
  //       "night",
  //       "celebrate",
  //       "autumn",
  //       "sparkler",
  //       "inspiration",
  //       "gravel",
  //       "leaves",
  //       "nature",
  //       "firework",
  //       "sparkle",
  //       "light",
  //       "adventure",
  //       "season",
  //       "woods",
  //       "flora",
  //       "celebration",
  //       "bokeh",
  //       "spark",
  //       "atmosphere of earth",
  //     ],
  //   },
  // ];
  //------- Tinder Card Set up -----------------//
  const [currentIndex, setCurrentIndex] = useState(imageSample.length - 1);
  const [lastDirection, setLastDirection] = useState();
  // used for outOfFrame closure
  const currentIndexRef = useRef(currentIndex);

  const childRefs = useMemo(
    () =>
      Array(imageSample.length)
        .fill(0)
        .map((i) => React.createRef()),
    []
  );

  const updateCurrentIndex = (val) => {
    setCurrentIndex(val);
    currentIndexRef.current = val;
  };

  const canGoBack = currentIndex < imageSample.length - 1;
  const canSwipe = currentIndex >= 0;

  // set last direction and decrease current index
  const swiped = (direction, nameToDelete, index) => {
    setLastDirection(direction);
    updateCurrentIndex(index - 1);
  };

  const outOfFrame = (name, idx) => {
    console.log(`${name} (${idx}) left the screen!`, currentIndexRef.current);
    // handle the case in which go back is pressed before card goes outOfFrame
    currentIndexRef.current >= idx && childRefs[idx].current.restoreCard();
    // TODO: when quickly swipe and restore multiple times the same card,
    // it happens multiple outOfFrame events are queued and the card disappear
    // during latest swipes. Only the last outOfFrame event should be considered valid
  };

  const swipe = async (dir) => {
    console.log("swipe");
    if (canSwipe && currentIndex < imageSample.length) {
      await childRefs[currentIndex].current.swipe(dir); // Swipe the card!
    }
  };

  const goBack = async () => {
    console.log("back");
    if (!canGoBack) return;
    const newIndex = currentIndex + 1;
    updateCurrentIndex(newIndex);
    await childRefs[newIndex].current.restoreCard();
  };
  //------- END OF - Tinder Card Set up - END OF ------------------//

  //Getting 10 random images

  //Hooks
  useEffect(() => {
    const getImageSample = async () => {
      try {
        setLoading(true);
        setProgress(0);

        const progressInterval = setInterval(() => {
          setProgress((prev) => (prev < 90 ? prev + 10 : prev));
        }, 200);

        const response = await axios.get(`${API_URL}/image/random`);
        console.log("image sample =", response.data);
        setImageSample(response.data);

        clearInterval(progressInterval);
        setProgress(100);
      } catch (error) {
        console.log("Error getting image sample:", error);
      } finally {
        setLoading(false);
      }
    };
    getImageSample();
  }, []);

  if (loading || imageSample.length === 0) {
    return <div>Loading...</div>;
  }

  return (
    <div className="flex  flex-col justify-center items-center">
      <h1 className="text-3xl p-7 font-semibold uppercase">
        Curate Your World
      </h1>

      <h3 className="text-center text-base w-3/5">
        Discover Your Next Favorite Artwork! 🎨 Swipe right to add stunning
        creations to your collection or left to pass. Let your taste shape your
        unique gallery!"
      </h3>
      {/* Loding container */}
      {(loading || imageSample.length < 10) && (
        <h3 className="text-center text-base w-3/5">Loading...</h3>
      )}
      {/* SwapContainer */}
      {/* Wait for loading image is finished */}
      {!loading && imageSample.length === 10 && (
        <div className="flex flex-col">
          <div className=" m-9 w-[90vw] max-w-[260px] h-[300px] flex flex-col items-center">
            {imageSample &&
              imageSample.map((image, index) => {
                return (
                  <TinderCard
                    ref={childRefs[index]}
                    className=" absolute"
                    key={image._id}
                    onSwipe={(dir) => swiped(dir, image._id, index)}
                    onCardLeftScreen={() => outOfFrame(image._id, index)}
                  >
                    <Card className="relative w-[80vw] max-w-[300px] h-[300px] bg-white rounded-2xl shadow-lg overflow-hidden">
                      <img
                        src={image.photo_image_url}
                        alt="Card image"
                        className="w-full h-full object-cover"
                      />
                    </Card>
                  </TinderCard>
                );
              })}
          </div>
          <div className="flex justify-between items-center">
            <div>
              <Button className="w-24" onClick={() => swipe("left")}>
                Ouuuh
              </Button>
            </div>
            <div>
              <Button onClick={() => goBack()}>Undo</Button>
            </div>
            <div>
              <Button className="" onClick={() => swipe("right")}>
                Love it!
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ShufflePage;
